DROP TABLE MEMBER_BOARD CASCADE CONSTRAINTS;
CREATE TABLE MEMBER_BOARD(
UN_MEM NUMBER(6),
ADMIN_MEM VARCHAR2(10) DEFAULT 'N' not null,
ID_MEM VARCHAR2(20) NOT NULL,
NN_MEM VARCHAR2(30) NOT NULL,
PW_MEM VARCHAR2(30) NOT NULL,
NAME_MEM VARCHAR2(120) NOT NULL,
EMAIL_MEM VARCHAR2(40) NOT NULL,
GENDER_MEM VARCHAR2(20) NOT NULL,
TEL_MEM VARCHAR2(20) NOT NULL, 
ZIPCODE_MEM VARCHAR2(10) NOT NULL,
ZC1_MEM VARCHAR2(500) NOT NULL,
ZC2_MEM VARCHAR2(500) NOT NULL,
JOIN_MEM VARCHAR2(10) NOT NULL,
DATE_MEM DATE DEFAULT SYSDATE,
CONSTRAINT MEMBERBOARD_PK PRIMARY KEY (UN_MEM)
);
select * from MEMBER_BOARD;




DROP TABLE USER_BOARD CASCADE CONSTRAINTS;
CREATE TABLE USER_BOARD(
UN_MEM NUMBER(6) CONSTRAINT USERBOARD_UN_FK REFERENCES MEMBER_BOARD(UN_MEM) ON DELETE CASCADE,
IDX_UT NUMBER(6),
NN_MEM VARCHAR2(30) NOT NULL,
WSUBJECT_UT VARCHAR2(50) NOT NULL, 
WCONTENT_UT VARCHAR2(4000) NOT NULL,
DATE_UT DATE DEFAULT SYSDATE,
READCOUNT_UT NUMBER(6) DEFAULT 0 NOT NULL,
REPLYCNT_UT NUMBER(6) DEFAULT 0 NOT NULL,
CONSTRAINT USERBOARD_PK PRIMARY KEY (IDX_UT)
);
select * from USER_BOARD;






DROP TABLE QA_BOARD CASCADE CONSTRAINTS;
CREATE TABLE QA_BOARD(
UN_MEM NUMBER(6) CONSTRAINT QABOARD_UN_FK REFERENCES MEMBER_BOARD(UN_MEM) ON DELETE CASCADE,
IDX_QT NUMBER(6),
NN_MEM VARCHAR2(30) NOT NULL,
WSUBJECT_QT VARCHAR2(50) NOT NULL, 
WCONTENT_QT VARCHAR2(4000) NOT NULL,
REF_QT NUMBER(6),
STEP_QT NUMBER(3) default 0 not null,
DEPTH_QT NUMBER(3) default 0 not null,
DATE_QT DATE DEFAULT SYSDATE,
READCOUNT_QT NUMBER(6) DEFAULT 0 NOT NULL,
CONSTRAINT QABOARD_PK PRIMARY KEY (IDX_QT)
);
select * from QA_BOARD;




DROP TABLE FOOD_BOARD CASCADE CONSTRAINTS;
CREATE TABLE FOOD_BOARD(
IDX_LI NUMBER(6),
UN_MEM NUMBER(6) CONSTRAINT FOODBOARD_UN_FK REFERENCES MEMBER_BOARD(UN_MEM) ON DELETE CASCADE,
NN_MEM VARCHAR2(30) NOT NULL,
CATEGORY_LI VARCHAR2(20) NOT NULL,
WSUBJECT_LI VARCHAR2(50) NOT NULL, 
TAG_LI VARCHAR2(500) NOT NULL,
THUMB_LI VARCHAR2(500),
WCONTENT_LI VARCHAR2(4000) NOT NULL,
DATE_LI DATE DEFAULT SYSDATE,
READCOUNT_LI NUMBER(6) DEFAULT 0 NOT NULL,
RECOMMEND_CNT NUMBER(6) DEFAULT 0 NOT NULL,
BOARD_NUM NUMBER(6) DEFAULT 0 NOT NULL,
REPLY_CNT NUMBER(6) DEFAULT 0 NOT NULL,
CONSTRAINT FOODBOARD_PK PRIMARY KEY (IDX_LI)
);
select * from FOOD_BOARD;





DROP TABLE RECOMMEND_BOARD CASCADE CONSTRAINTS;
CREATE TABLE RECOMMEND_BOARD(
IDX_NUM NUMBER(6),
ID_MEM VARCHAR(20) not null,
BOARD_NUM NUMBER(6)
);
select * from RECOMMEND_BOARD;






DROP TABLE REPLY_BOARD1;
CREATE TABLE reply_board1(
  idx_reply NUMBER PRIMARY KEY,
  mem_reply number(6) not null,
  nn_reply VARCHAR2(30) NOT NULL,
  content_reply VARCHAR2(2000) NOT NULL,
  date_reply DATE NOT NULL,
  board_reply NUMBER NOT NULL,
  BOARD_NUM NUMBER(6));
select * from reply_board1;



DROP TABLE REPLY_BOARD2;
CREATE TABLE reply_board2(
  idx_reply NUMBER PRIMARY KEY,
  mem_reply number(6) not null,
  nn_reply VARCHAR2(30) NOT NULL,
  content_reply VARCHAR2(2000) NOT NULL,
  date_reply DATE NOT NULL,
  board_reply NUMBER NOT NULL,
CONSTRAINT reply_fk FOREIGN KEY(idx_reply)
REFERENCES food_board(idx_li) ON DELETE CASCADE);
select * from reply_board2;





DROP TABLE TAG_BOARD CASCADE CONSTRAINTS;
CREATE TABLE TAG_BOARD(
IDX_TAG NUMBER(6),
IDX_LI NUMBER(6) CONSTRAINT TAGBOARD_IDX_FK REFERENCES FOOD_BOARD(IDX_LI) ON DELETE CASCADE,
MYTAG1_TAG VARCHAR2(100) NOT NULL,
MYTAG2_TAG VARCHAR2(100),
MYTAG3_TAG VARCHAR2(100),
MYTAG4_TAG VARCHAR2(100),
MYTAG5_TAG VARCHAR2(100),
MYTAG6_TAG VARCHAR2(100),
MYTAG7_TAG VARCHAR2(100),
MYTAG8_TAG VARCHAR2(100),
MYTAG9_TAG VARCHAR2(100),
MYTAG10_TAG VARCHAR2(100),
CONSTRAINT TAGBOARD_PK PRIMARY KEY (IDX_TAG)
);
select * from TAG_BOARD;




SELECT GOOD_SEQ.NEXTVAL FROM GOOD_BOARD WHERE GOOD_TB;
SELECT GOOD_SEQ.NEXTVAL FROM FOOD_BOARD WHERE WNUM_LI;


----------------- 위에까지 테이블 생성 완료 -----------------
CREATE SEQUENCE  "SCOTT"."CONTENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SCOTT"."GOOD_SEQ"  MINVALUE 0 MAXVALUE 1 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE ;




------------------------ 시퀀스-----------------------------

SELECT CONTENT_SEQ.NEXTVAL WNUM_LI FROM FOOD_BOARD; --시퀀스 특정 컬럼 적용 확인문 -- 

insert into FOOD_BOARD(IDX_LI) values(FOOD_SEQ.NEXTVAL);
select CONTENT_SEQ.NEXTVAL from dual;

insert into  MEMBER_BOARD values('1111', 'Y', 'aaaa1111', '닉네임', '1234', '가가가', 'seong@naver.com', 'M', '010-0000-0000', '1110000', '영등포', '글로벌인', 'Y', '2021-12-30'); 

insert into FOOD_BOARD values(0011, 1111, '닉네임', '김치', '한국인의 국룰', '썸네일 경로1', '가나다라마바사', 'ㅇㅈ?','2021-12-30', 1); 
insert into  FOOD_BOARD values(0012, 1111, '닉네임', '김치찌개', '킹갓갓개', '썸네일 경로2', 'ABCDEFG', 'ㅇㅇㅈ', '2021-12-31', 2); 
insert into  FOOD_BOARD values(0013, 1111, '닉네임', '김치볶음밥', '맛있음', '썸네일 경로3', 'HAHAHA', 'ㄹㅇㅋㅋ', '2022-01-01', 3); 


insert into user_board values(1111, 15, 'name2', 'sub2', 'con2', 'dd', '2022-01-06', 0);
insert into user_board values(1111, 12, '네임2', '제목2', '내용2', 'dd', '2022-01-06', 0);
insert into user_board values(1111, 16, 'name2', 'sub2', 'con2', 'ddd', '2022-01-06', 0);
insert ignore into user_board values(1111, 17, 'name2', 'sub2', 'con2', '2022-01-06', 0);
insert into qa_board values(1111, 11, '네임', '제목', '내용', 0, 0, 0, '2022-01-06', 0);
insert into qa_board values(1111, 12, '네임', '제목', '내용', 0, 0, 0, '2022-01-06', 0);

select un_mem, nn_mem from user_board;


--------------------------- 테스트 데이터 -------------------------------

DELETE FOOD_BOARD WHERE IDX_LI = 11;

DELETE MEMBER_BOARD WHERE UN_MEM = 1111;

------------------ 데이터삭제 쿼리문 -----------------------------
commit;